# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 709401693ad8d191190d84d50df11d8de121f59e2079810e5f9119d26b55bd216898ebbcb55f2618b0078601093a242da9cc7ec10a3fb72db4e298832a7be8f5

test:
  secret_key_base: 27331e42558aba07b69734bb542794c28a4cfc452701f1aa210755e98c2ddc0dfe527d141629aaa8085928dae7a81286738f79c983e12a580215d8febe1a7db4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
